server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&serverTimezone=UTC
    username: root
    password: "123456"
  redis:
    host: localhost
    port: 6379
    password: "123456"
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      eager: true
  elasticsearch:
    uris: http://localhost:9200
    socket-timeout: 5000
    connection-timeout: 5000
sentinel:
  flow:
    concurrency-threshold: 2200
  system:
    cpu-usage: 0.95

csp:
  sentinel:
    log:
      dir: logs/sentinel
      use-pid: true
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
# Canal配置
canal:
  host: localhost
  port: 11111
  destination: travelshop
  username: 
  password:
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin  # 调度中心地址
    accessToken: default_token  # 鉴权token
    executor:
      appname: travelshop-job-executor  # 执行器名称
      ip:  # 可自动获取
      port: 9999  # 执行器端口
      logpath: /logs/xxl-job/jobhandler  # 日志路径
      logretentiondays: 30  # 日志保留天数